#!/usr/bin/env python3

import logging
import ast
import os

from paho.mqtt import client
from influxdb import InfluxDBClient

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger("listener")

influx_client = InfluxDBClient('influxdb', 8086, database="weather")


def on_connect(client, userdata, flags, rc):
    client.subscribe(
        [
            ("home/temp", 0),
            ("home/humidity", 0),
            ("home/pressure", 0),
        ]
    )


def on_message(client, userdata, message):
    data, sensor = message.payload.decode().split(",")
    payload = ast.literal_eval(data)
    logger.info("%s=%s from sensor=%s", message.topic, payload, sensor)

    json_body = [
        dict(
            measurement=message.topic.split("/")[-1],
            tags={"sensor": sensor},
            fields={"value": payload}
        )
    ]

    influx_client.write_points(json_body)


def main():
    mqtt = client.Client()
    mqtt.on_connect = on_connect
    mqtt.on_message = on_message
    mqtt.connect("broker")
    mqtt.loop_forever()


if __name__ == "__main__":
    main()
